const SCHEMA = "static-collective/human-witness-event/v0";
const DISPOSITIONS = new Set(["pass", "fail", "ambiguous"]);
const ERRORS = Object.freeze({
  IDENTITY_MISSING: "WITNESS_EXECUTION_IDENTITY_MISSING",
  EVENT_INVALID: "WITNESS_EVENT_INVALID",
  DISPOSITION_INVALID: "WITNESS_DISPOSITION_INVALID",
  FORBIDDEN_MATERIAL: "WITNESS_FORBIDDEN_MATERIAL",
  TARGET_UNKNOWN: "WITNESS_TARGET_UNKNOWN",
});

module.exports = { SCHEMA, DISPOSITIONS, ERRORS };
